framework:
    validation:
        enabled: true
        auto_mapping:
            - App\Entity
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            enabled: true
            auto_mapping:
                - App\Entity
            not_compromised_password: false
